name 'tranSMART'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'support@eaglegenomics.com'
description 'Installs tranSMART'
version '0.2.1'

depends 'apt'
depends 'build-essential'
depends 'git'
depends 'magic_shell'
